### PR TITLE
Add swagger config

### PR DESCRIPTION
**Pull request by superkhau**
See https://github.com/strongloop/loopback-swagger/issues/52#issuecomment-237873507

### CODE REVIEW

**Comment by superkhau** [comment]
@bajtos @sam-github PTAL

**Comment by bajtos** [comment]
LGTM.

Please check why the build is failing on `loopback-example-ssl/node=0.10,os=macos`

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@bajtos It's good now, just a random error on CI. Reran and it's green, confirmed with @rmg too.

**Pull request merged**
