### PR TITLE
Add jshint

### PR DESCRIPTION
**Pull request by ritch**
/to @raymondfeng

### CODE REVIEW

**Comment by raymondfeng** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Of course, now it needs to actually pass `jshint`...

**Comment by rmg** [comment]
@ritch I went ahead and cleaned this up and landed it because it is blocking PR builds for all the modules it depends on.

**Comment by ritch** [comment]
Thanks @rmg

**Pull request merged**
